import { supabase } from "@/integrations/supabase/client";
import type { TablesInsert } from "@/integrations/supabase/types";
import { Enums } from "@/integrations/supabase/types";

type UserRole = Enums<"user_role">;

export const signUpUser = async (email: string, password: string) => {
  console.log("Attempting to sign up user with email:", email);
  try {
    const { data, error } = await supabase.auth.signUp({
      email,
      password,
      options: {
        emailRedirectTo: `${window.location.origin}/admin`,
      },
    });

    if (error) {
      console.error("Sign up error:", error);
      
      // Try to parse the error response body if it exists
      let parsedBody;
      try {
        if (error.message) {
          const bodyMatch = error.message.match(/\{.*\}/);
          if (bodyMatch) {
            parsedBody = JSON.parse(bodyMatch[0]);
          }
        }
      } catch (e) {
        console.error("Error parsing response body:", e);
      }

      // Check for rate limit error in multiple places
      if (error.status === 429 || 
          (parsedBody?.code === 'over_email_send_rate_limit') ||
          error.message?.includes('rate limit')) {
        throw new Error("Too many registration attempts. Please try again in a few minutes.");
      }

      // Handle other known error cases
      if (error.message?.includes('already registered')) {
        throw new Error("This email is already registered. Please try logging in instead.");
      }

      // For unknown errors, throw a generic message
      throw new Error("Registration failed. Please try again later.");
    }

    console.log("Sign up successful:", data);
    return data;
  } catch (error) {
    console.error("Sign up error:", error);
    throw error;
  }
};

export const createUserProfile = async (userId: string, email: string) => {
  console.log("Creating user profile for:", userId);
  
  // First, get the current session to ensure we're authenticated
  const { data: { session }, error: sessionError } = await supabase.auth.getSession();
  
  if (sessionError || !session) {
    console.error("Session error:", sessionError);
    throw new Error("No valid session found");
  }

  const profileData: TablesInsert<'profiles'> = {
    id: userId,
    user_id: userId,
    email,
    role: 'member' as UserRole,
    created_at: new Date().toISOString(),
    updated_at: new Date().toISOString()
  };

  const { data, error } = await supabase
    .from('profiles')
    .insert(profileData)
    .select()
    .single();

  if (error) {
    console.error("Profile creation error:", error);
    throw error;
  }

  console.log("Profile created successfully:", data);
  return data;
};

export const createMember = async (memberData: any, collectorId: string) => {
  console.log("Creating member with data:", { memberData, collectorId });
  
  const memberObject: TablesInsert<'members'> = {
    collector_id: collectorId,
    full_name: memberData.fullName,
    email: memberData.email,
    phone: memberData.mobile,
    address: memberData.address,
    town: memberData.town,
    postcode: memberData.postCode,
    date_of_birth: memberData.dob,
    gender: memberData.gender,
    marital_status: memberData.maritalStatus,
    status: 'pending',
    profile_updated: true,
    member_number: '', // This will be auto-generated by the database trigger
    created_at: new Date().toISOString(),
    updated_at: new Date().toISOString()
  };

  const { data, error } = await supabase
    .from('members')
    .insert(memberObject)
    .select()
    .single();

  if (error) {
    console.error("Member creation error:", error);
    throw error;
  }

  console.log("Member created successfully:", data);
  return data;
};

export const createRegistration = async (memberId: string) => {
  console.log("Creating registration for member:", memberId);
  
  const { data, error } = await supabase
    .from('registrations')
    .insert({
      member_id: memberId,
      status: 'pending',
      created_at: new Date().toISOString(),
      updated_at: new Date().toISOString()
    })
    .select()
    .single();

  if (error) {
    console.error("Registration creation error:", error);
    throw error;
  }

  console.log("Registration created successfully:", data);
  return data;
};
